name: Run Crawler Every 4 Hours

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create ID.txt if not exists
        run: touch ID.txt

      # ----------------- 이 부분이 핵심입니다 -----------------
      - name: Run crawler script
        # .env 파일을 만드는 대신, env 키워드로 직접 환경 변수를 주입합니다.
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_CHANNEL_ID_CRAWLER: ${{ secrets.CHAT_ID }}
          SEEN_NOTICE_FILE: ID.txt
          # 파이썬 코드에서 사용하는 다른 환경 변수들도 여기에 추가하세요.
        run: python crawler.py
      # ----------------------------------------------------

      - name: Commit and push ID.txt changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add ID.txt
          # 변경 사항이 있을 때만 커밋하도록 수정
          if ! git diff --staged --quiet; then
            git commit -m "Update seen notices"
            git push
          fi