name: Run Crawler Every 4 Hours

on:
  schedule:
    - cron: '0 */4 * * *'  # 4시간마다 실행
  workflow_dispatch:  # 수동 실행 옵션

permissions:
  contents: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 깊이 있는 체크아웃

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Create ID.txt if not exists
        run: touch ID.txt
        
      - name: Create .env file
        run: |
          echo "tele_api=${{ secrets.TELEGRAM_API_KEY }}" > teleapi_key/.env

      - name: Run crawler script
        run: python crawler.py
        
      - name: Commit and push ID.txt changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add ID.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ID.txt with new hashes"
          git push
